### ISSUE TITLE
Doesn't colorifying few parts

### ISSUE THREAD

**Issue by ldemattos** [mlinksva/language-wdiff#6]
I'm obtaining some unexpected results.

![image](https://cloud.githubusercontent.com/assets/23236474/25646758/cf33ef54-2f91-11e7-9569-1724803d2e08.png)

**Comment by mlinksva** [comment]
Hmm, I'm not sure what would cause that. Any chance you could attach a `.wdiff` file you get that behavior with? Thanks for the bug report!

**Comment by ldemattos** [comment]
I'm the one who should say thanks here!

Follows the wdiff file as requested:
[https://gist.github.com/ldemattos/31b0ec3a5c9d5eec83aa6d8f18f5dbfc](https://gist.github.com/ldemattos/31b0ec3a5c9d5eec83aa6d8f18f5dbfc)

Thanks in advance!

**Comment by mlinksva** [comment]
It's not matching after the first 1000 characters on a line. I'm not sure why yet.

It's also overmatching anything in between curly brackets rather than only between curly brackets and plusses, oops.

The second should be a simple escaping of the `+`'s at https://github.com/mlinksva/language-wdiff/blob/b02c5083ac0169dca266c94d022546f0355446ed/grammars/wdiff.cson#L11

I'll see if I can fix both and get a new release out.

**Comment by mlinksva** [comment]
@ldemattos only matching against first 1000 characters of a line by default seems to have been added at https://github.com/atom/atom/pull/13898/files#diff-f19c9794e75cf52bae5aa30d1bdb40fcR18 but can be opted out of so that's what I made this package do. Should be fixed in v0.3.3 if you upgrade to that.

**Comment by ldemattos** [comment]
hey, @mlinksva ! it seems to be perfectly working now! Thank you very much!
